# Generated by Django 5.0.6 on 2024-06-17 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customauth', '0002_alter_customuser_options_customuser_avatar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date_joined'),
        ),
    ]
