# Generated by Django 5.0.6 on 2024-07-18 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_address_phone_no'),
        ('accounts', '0007_alter_address_county_alter_address_title'),
    ]

    operations = [
    ]
