# Generated by Django 5.0.6 on 2024-06-14 08:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('description', models.TextField(blank=True)),
                ('price', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0, 'Price cannot be negative!')])),
                ('stock_count', models.IntegerField(default=1)),
                ('slug', models.SlugField(max_length=48, unique=True)),
                ('active', models.BooleanField(default=True)),
                ('on_sale', models.BooleanField(default=False)),
                ('featured', models.BooleanField(default=False)),
                ('date_uploaded', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
