# Generated by Django 5.0.6 on 2024-06-14 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_productimage_image_productimage_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='thumbnail',
            field=models.ImageField(default=None, null=True, upload_to='product-thumbnails'),
        ),
    ]
